name: Fetch Mapping

run-name: Fetch Mapping

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: write

concurrency:
  group: "mapping"
  cancel-in-progress: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Fetch Mapping
        run: |
          deno run --allow-write --allow-net ./.github/workflows/fetchMapping.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: mapping.json

  commit:
    runs-on: ubuntu-latest
    needs: download
    strategy:
      matrix:
        branch: [main, dev]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: src/assets

      - name: Move File to Proper Location
        run: |
          cd src/assets
          mv artifact/mapping.json mapping.json

      - name: Commit File to ${{ matrix.branch }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Mapping
